# Dual-Augmented Agent配置 - 知识图谱 + 记忆系统
# 用于测试两种能力的协同效果

agent_name: "dual_augmented"
agent_type: "UnifiedKGAgent"
description: "Agent with both knowledge graph and memory capabilities"

# LLM基础配置
model_name: "gpt-4o"
temperature: 0.7
max_tokens: 300

# 能力开关
capabilities:
  use_knowledge_graph: true
  use_memory: true
  use_enhanced_reasoning: false
  use_rl: false

# 知识图谱配置
knowledge_graph:
  enabled: true
  update_dynamically: true
  max_facts_per_query: 5
  query_types: ["keywords", "dodaf", "entity"]
  dodaf_enabled: true
  confidence_threshold: 0.5

# 记忆系统配置
memory:
  enabled: true
  use_short_term: true
  use_medium_term: true
  use_long_term: false
  short_term_size: 10
  medium_term_size: 50
  similarity_threshold: 0.6
  max_retrieved_memories: 5

# 实验标签
experiment_tags:
  - "dual_capability"
  - "kg_memory_combo"
  - "no_reasoning"

# 预期性能
expected_performance:
  success_rate: 0.65 # 预期协同效果
  avg_steps: 16      # 预期显著减少步数
  efficiency: 0.6    # 预期高效率
