# Fully-Augmented Agent配置 - 所有能力启用
# 用于测试完整系统的最佳性能

agent_name: "fully_augmented"
agent_type: "UnifiedKGAgent"
description: "Complete system with all capabilities enabled"

# LLM基础配置
model_name: "gpt-4o"
temperature: 0.7
max_tokens: 300

# 能力开关 - 全部启用
capabilities:
  use_knowledge_graph: true
  use_memory: true
  use_enhanced_reasoning: true
  use_rl: false

# 知识图谱配置
knowledge_graph:
  enabled: true
  update_dynamically: true
  max_facts_per_query: 5
  query_types: ["keywords", "dodaf", "entity"]
  dodaf_enabled: true
  confidence_threshold: 0.5

# 记忆系统配置
memory:
  enabled: true
  use_short_term: true
  use_medium_term: true
  use_long_term: true  # 完整系统启用长期记忆
  short_term_size: 10
  medium_term_size: 50
  long_term_size: 100
  similarity_threshold: 0.6
  max_retrieved_memories: 5

# 推理增强配置
reasoning:
  enabled: true
  use_react: true
  use_dodaf: true
  use_chain_of_thought: true
  max_react_iterations: 5
  react_temperature: 0.7

# 实验标签
experiment_tags:
  - "full_system"
  - "all_capabilities"
  - "maximum_enhancement"

# 预期性能
expected_performance:
  success_rate: 0.8  # 预期最高成功率
  avg_steps: 12      # 预期最少步数
  efficiency: 0.8    # 预期最高效率
