# Vanilla LLM Agent配置 - 纯LLM，无任何增强功能
# 用于建立性能基准

agent_name: "vanilla_llm"
agent_type: "UnifiedKGAgent"
description: "Pure LLM baseline agent without any enhancements"

# LLM基础配置
model_name: "gpt-4o"
temperature: 0.7
max_tokens: 300

# 能力开关 - 全部关闭
capabilities:
  use_knowledge_graph: false
  use_memory: false
  use_enhanced_reasoning: false
  use_rl: false

# 实验标签
experiment_tags:
  - "baseline"
  - "llm_only"
  - "no_enhancement"

# 预期性能（用于对比）
expected_performance:
  success_rate: 0.3  # 预期成功率
  avg_steps: 25      # 预期平均步数
  efficiency: 0.2    # 预期效率
