# 联合检索更新模式配置
# 在同一回合内同时进行知识检索和更新

mode_name: "joint_retrieve_update"
description: "Joint retrieval and update mode - both operations in the same turn"

# 模式控制
mode_control:
  strategy: "joint"
  coordination: "parallel"  # parallel, sequential, adaptive
  
  # 联合操作配置
  joint_operations:
    retrieve_first: true
    update_based_on_retrieval: true
    feedback_loop: true
    max_iterations: 3

# 检索配置
retrieval:
  enabled: true
  
  # 检索策略
  strategy: "context_aware"  # context_aware, similarity_based, graph_walk
  max_retrieved_items: 5
  confidence_threshold: 0.6
  
  # 检索触发条件
  triggers:
    - "new_observation"
    - "uncertainty_high"
    - "knowledge_gap_detected"
  
  # 检索范围
  scope:
    include_entities: true
    include_relations: true
    include_facts: true
    temporal_window: 10  # steps

# 更新配置
update:
  enabled: true
  
  # 更新策略
  strategy: "evidence_based"  # evidence_based, confidence_based, consensus
  confidence_threshold: 0.8
  
  # 更新触发条件
  triggers:
    - "new_evidence"
    - "contradiction_detected"
    - "confidence_increase"
  
  # 更新类型
  update_types:
    - "add_fact"
    - "modify_confidence"
    - "add_relation"
    - "update_entity_properties"
  
  # 冲突解决
  conflict_resolution:
    method: "weighted_evidence"  # weighted_evidence, temporal_priority, source_reliability
    keep_history: true
    max_conflicting_facts: 3

# 协调机制
coordination:
  # 检索-更新协调
  retrieve_update_sync:
    enabled: true
    sync_method: "feedback_loop"
    max_sync_iterations: 2
  
  # 质量控制
  quality_control:
    enabled: true
    min_evidence_strength: 0.5
    consistency_check: true
    
  # 性能优化
  performance:
    batch_operations: true
    cache_retrievals: true
    parallel_processing: false

# 阈值和门控
thresholds:
  # 检索阈值
  retrieval_thresholds:
    similarity_min: 0.5
    relevance_min: 0.6
    confidence_min: 0.4
  
  # 更新阈值
  update_thresholds:
    evidence_strength_min: 0.7
    confidence_change_min: 0.1
    consistency_score_min: 0.6

# 监控和日志
monitoring:
  enabled: true
  
  # 性能监控
  performance_metrics:
    - "retrieval_latency"
    - "update_latency"
    - "joint_operation_time"
    - "cache_hit_rate"
  
  # 质量监控
  quality_metrics:
    - "retrieval_precision"
    - "update_accuracy"
    - "consistency_score"
    - "knowledge_growth_rate"
  
  # 日志配置
  logging:
    log_retrievals: true
    log_updates: true
    log_coordination: true
    log_conflicts: true
    detail_level: "medium"  # low, medium, high

# 实验标签
experiment_tags:
  - "joint_mode"
  - "retrieve_update"
  - "coordination"
  - "real_time"

# 环境适配
environment_adaptation:
  observation_enhancement: true
  action_space_modification: false
  reward_signal_integration: true
